:queues:
  - default
  - mailers
:schedule:
  process_recurring_donor:
    cron: '0 0-23 * * *'
    class: ProcessRecurringDonorsJob
  process_iats:
    cron: '0 18 * * * America/Toronto'
    class: ProcessIatsJob